<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>【一步一步了解Java系列】：认识异常类 - 编程大咖</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:url" content="https://bcdaka.github.io/posts/349e3dcef38ac491e3b203e7c383fb7d/">
  <meta property="og:site_name" content="编程大咖">
  <meta property="og:title" content="【一步一步了解Java系列】：认识异常类">
  <meta property="og:description" content="看到这句话的时候证明：此刻你我都在努力
加油陌生人
个人主页：Gu Gu Study
专栏：一步一步了解Java
喜欢的一句话： 常常会回顾努力的自己，所以要为自己的努力留下足迹
喜欢的话可以点个赞谢谢了。
作者：小闭
异常类的概念及其层次结构 Java中存在异常类，那么何为异常类呢？那么我们必须先了解一下它的概念：Java异常处理是Java语言中非常重要的一部分，它允许程序在遇到错误时能够优雅地处理问题而不是直接崩溃。Java异常类主要分为两大类：检查型异常（Checked Exceptions）和非检查型异常（Unchecked Exceptions）。
检查型异常/编译时异常（Checked Exceptions）： 这些异常通常是由于编程错误导致的，比如FileNotFoundException或SQLException。它们必须在方法签名中声明抛出，或者在方法内部被处理（通常是通过try-catch块）。在运行前编译器就已经报出警告了： 非检查型异常/运行时异常（Unchecked Exceptions）： 这些异常通常是由于运行时错误导致的，比如NullPointerException或ArithmeticException。它们不需要在方法签名中声明，也不强制要求必须被捕获处理。如图在运行前编译器是不会提示错误的： Java中的异常就像我们生活中人生病一样，我们的程序也会生病，我们可以把计算机的病就叫做“异常”。
那么下面就给大家解析一下其层次结构：
Java异常类的层次结构从__java.lang__包中的__Throwable__类开始，它有两个主要的子类：Exception__和__Error。
Throwable： Java异常类的根类。有两个重要的子类：Exception和Error。 Exception： 表示程序本身可以处理的异常情况。进一步分为IOException、SQLException等。 RuntimeException： Exception的一个子类，表示在Java程序运行时发生的异常。包括NullPointerException、IndexOutOfBoundsException等。 Error： 表示JVM无法处理的错误，比如OutOfMemoryError或StackOverflowError。通常不需要程序去捕获这些错误 有关处理异常的关键词 在Java中处理异常我们有这么几个常用的关键词 ：throw、try、catch、finally、throws。
** throw 抛出异常 ** 如下是一个简单的异常抛出，我们在一个方法中要执行一条语句时，如果其可能会发生异常，如：null，分母为0，数组访问越界，我们都可以自己抛出异常，如下为一个空指针异常
package demo1; public class Test { public static void testExceptinon(int[] arr){ if(arr==null){ throw new ArithmeticException(); } } public static void main(String[] args) { int[] arr=null; testExceptinon(arr); } } 所谓抛出异常其实就是抛出一个Exception或Exception的子类。
注意事项：">
  <meta property="og:locale" content="zh_CN">
  <meta property="og:type" content="article">
    <meta property="article:section" content="posts">
    <meta property="article:published_time" content="2024-06-22T09:22:15+08:00">
    <meta property="article:modified_time" content="2024-06-22T09:22:15+08:00">

	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
  


</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大咖" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大咖</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">【一步一步了解Java系列】：认识异常类</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="markdown_views prism-atom-one-dark">
                    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                        <path stroke-linecap="round" d="M5,0 0,2.5 5,5z" id="raphael-marker-block" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></path>
                    </svg>
                    <p><strong>看到这句话的时候证明：此刻你我都在努力</strong><br> <strong>加油陌生人</strong><br> <img src="https://images2.imgbox.com/1d/c0/VK88uV5H_o.png" alt="微信图片编辑_20240229212205.png"><br> <br><strong>个人主页：</strong><a href="https://blog.csdn.net/2302_81249757?type=lately"><strong>Gu Gu Study</strong></a><strong><br><strong>专栏：</strong><a href="https://blog.csdn.net/2302_81249757/category_12656486.html?spm=1001.2014.3001.5482"><strong>一步一步了解Java</strong></a><br><br> 喜欢的一句话： 常常会回顾努力的自己，所以要为自己的努力留下足迹</strong><br> <br><strong>喜欢的话可以点个赞谢谢了。</strong><br> <strong>作者：小闭</strong></p> 
<hr> 
<h2><a id="_11"></a>异常类的概念及其层次结构</h2> 
<p>Java中存在异常类，那么何为异常类呢？那么我们必须先了解一下它的概念：<strong><em>Java异常处理是Java语言中非常重要的一部分，它允许程序在遇到错误时能够优雅地处理问题而不是直接崩溃。Java异常类主要分为两大类：检查型异常（Checked Exceptions）和非检查型异常（Unchecked Exceptions）。</em></strong></p> 
<ol><li><strong>检查型异常/编译时异常（Checked Exceptions）</strong>： 
  <ul><li>这些异常通常是由于编程错误导致的，比如FileNotFoundException或SQLException。</li><li>它们必须在方法签名中声明抛出，或者在方法内部被处理（通常是通过try-catch块）。</li><li><strong>在运行前编译器就已经报出警告了：</strong></li><li><img src="https://images2.imgbox.com/73/11/s5SMUVcU_o.png" alt="image.png"></li></ul> </li><li><strong>非检查型异常/运行时异常（Unchecked Exceptions）</strong>： 
  <ul><li>这些异常通常是由于运行时错误导致的，比如NullPointerException或ArithmeticException。</li><li>它们不需要在方法签名中声明，也不强制要求必须被捕获处理。</li><li><strong>如图在运行前编译器是不会提示错误的：</strong><img src="https://images2.imgbox.com/63/6c/lH92ufqR_o.png" alt="image.png"></li></ul> </li></ol> 
<p>Java中的异常就像我们生活中人生病一样，我们的程序也会生病，我们可以把计算机的病就叫做“异常”。</p> 
<hr> 
<p>那么下面就给大家解析一下其层次结构：<br> <strong><em>Java异常类的层次结构从__java.lang__包中的__Throwable__类开始，它有两个主要的子类：<strong>Exception__和__Error</strong>。</em></strong></p> 
<ul><li>Throwable： 
  <ul><li>Java异常类的根类。</li><li>有两个重要的子类：Exception和Error。</li></ul> </li><li>Exception： 
  <ul><li>表示程序本身可以处理的异常情况。</li><li>进一步分为IOException、SQLException等。</li></ul> </li><li>RuntimeException： 
  <ul><li>Exception的一个子类，表示在Java程序运行时发生的异常。</li><li>包括NullPointerException、IndexOutOfBoundsException等。</li></ul> </li><li>Error： 
  <ul><li>表示JVM无法处理的错误，比如OutOfMemoryError或StackOverflowError。</li><li>通常不需要程序去捕获这些错误</li></ul> </li></ul> 
<hr> 
<h3><a id="_46"></a>有关处理异常的关键词</h3> 
<p>在Java中处理异常我们有这么几个常用的关键词 ：throw、try、catch、finally、throws。</p> 
<ol><li>** throw 抛出异常 **</li></ol> 
<p>如下是一个简单的异常抛出，我们在一个方法中要执行一条语句时，如果其可能会发生异常，如：null，分母为0，数组访问越界，我们都可以自己抛出异常，如下为一个空指针异常</p> 
<pre><code>package demo1;

public class Test {

    public static void testExceptinon(int[] arr){
        if(arr==null){
        throw new ArithmeticException();
    }
    }


    public static void main(String[] args) {
        int[] arr=null;
        testExceptinon(arr);
    }

}
</code></pre> 
<p><img src="https://images2.imgbox.com/97/68/CdDz1vi5_o.png" alt="image.png"><br> 所谓抛出异常其实就是抛出一个Exception或Exception的子类。<br> 注意事项：</p> 
<blockquote> 
 <p><strong>抛出异常类其必须是Exception或Exception的子类。</strong><br> <strong>抛出异常必须在方法内部</strong><br> <strong>如果抛出的是 RunTimeException 或者 RunTimeException 的子类，则可以不用处理，直接交给JVM来处理</strong><br> ** 如果抛出的是编译时异常，用户必须处理，否则无法通过编译**<br> ** 异常一旦抛出，其后的代码就不会执**</p> 
</blockquote> 
<hr> 
<ol start="2"><li><strong>异常声明throws</strong></li></ol> 
<p>throws一个用来声明异常的关键词，是用在方法上的，具体格式为<br> ** 修饰符 返回值类型 方法名(参数列表) throws 异常类型1，异常类型2…{ } **<br> <strong>注意throws只是起到警示作用，就是给程序员知道用这个方法可能会抛出异常。不会解决异常。</strong></p> 
<pre><code>public class Test {

    public static final void test1 ()throws RuntimeException{
        int a=10;
        int c=0;
        System.out.println(a/c);

    }



}
</code></pre> 
<ol start="3"><li>** try-catch捕获并处理 **</li></ol> 
<p>解决异常还得用到try-catch语句，这是我们常用处理异常的关键词，当然还有finally关键词，稍后我也会提到。</p> 
<pre><code>import com.sun.security.jgss.GSSUtil;

public class Test {

    public static final void test1 ()throws ArithmeticException{
        int a=10;
        int c=0;
        System.out.println(a/c);

    }

    public static void main(String[] args) {

        int q=10;
        int p=100;
        String s="hello world";
        System.out.println(q+p);
        try{
            test1();              //try的花括号内是放入可能会抛出异常的语句
                                  //如果里面的语句没有抛出异常则会跳出try-catch语句


        }catch (ArithmeticException e){   //小括号里是放入可能会捕捉到的异常类 e

            System.out.println("处理异常");  //catch花括号内是我们自行处理异常的方法

        }finally {
            System.out.println("无论是否捕捉到异常都一定会执行的代码");   //finally里的语句无论是否检测到异常都会执行的语句
        }

        System.out.println("处理完异常后的代码执行");  //这是处理异常后才会执行的语句
                                                 // 当异常被捕获到时，异常就被处理了，这里的后序代码一定会执行
                                               //如果捕获了，由于捕获时类型不对，那就没有捕获到，这里的代码就不会被执行


    }



}
</code></pre> 
<ol><li>try的花括号内是放入可能会抛出异常的语句， 如果里面的语句没有抛出异常则会跳出try-catch语句</li><li>catch的小括号里是放入可能会捕捉到的异常类 e，catch花括号内是我们自行处理异常的方法</li><li>catch-catch-finally外的语句：当异常被捕获到时，异常就被处理了，这里的后序代码一定会执行，如果捕获了，由于捕获时类型不对，那就没有捕获到，这里的代码就不会被执行</li></ol> 
<hr> 
<ol start="4"><li>** finally **</li></ol> 
<p>配合try-catch语句用的，但是其不是一定要加上去的，而try-catch一定是一起出现的。<br> 在写程序时，有些特定的代码，不论程序是否发生异常，都需要执行，比如程序中打开的资源：网络连接、数据库 连接、IO流等，在程序正常或者异常退出时，必须要对资源进进行回收。另外，因为异常会引发程序的跳转，可能 导致有些语句执行不到，finally就是用来解决这个问题的。</p> 
<pre><code>public static int getData() {
    Scanner sc = null;
    try {
        sc = new Scanner(System.in);
        int data = sc.nextInt();
        return data;
    } catch (InputMismatchException e) {
        e.printStackTrace();
    } finally {
        System.out.println("finally中代码");
    }
    System.out.println("try-catch-finally之后代码");
    if (null != sc) {
        sc.close();
    }


    return 0;
}

public static void main(String[] args) {
    int data = getData();
    System.out.println(data);
}
</code></pre> 
<p>上述程序，如果正常输入，成功接收输入后程序就返回了，try-catch-finally之后的代码根本就没有执行，即输入流 就没有被释放，造成资源泄漏。</p> 
<hr> 
<h4><a id="_191"></a>自定义异常类</h4> 
<p>使用的较多的异常类往往是我们自己定义的比较多，那么如何自定义异常类呢，下面我们就来讲讲如何自定义异常类。</p> 
<pre><code>class textException extends RuntimeException{

    public textException() {
    }

    public textException(String message) {
        super(message);
    }
}




public class Test1 {

    public static void main(String[] args) {
        int a=0;
        if(a==0){
            throw new textException();
        }
    }

}
</code></pre> 
<p><img src="https://images2.imgbox.com/a6/a9/myFuOwLd_o.png" alt="image.png"><br> 如上我们只需让自己创建出的类继承Exception或其它异常类即可，这样这个类也是一个异常类了。<br> 然后我们在需要抛出异常时，抛出自己定义的异常即可。<br> 也可以用try-catch进行使用解决自己定义的异常。<br> <strong><em>注意事项：</em></strong></p> 
<ul><li>** 自定义异常通常会继承自 Exception 或者 RuntimeException **</li><li>**继承自 Exception 的异常默认是受查异常 **</li><li>**继承自 RuntimeException 的异常默认是非受查异常 **</li></ul> 
<hr> 
<h5><a id="_231"></a>异常的处理流程</h5> 
<p>关于 “调用栈” 方法之间是存在相互调用关系的, 这种调用关系我们可以用 “调用栈” 来描述. 在 JVM 中有一块内存空间称为 “虚拟机栈” 专门存储方法之间的调用关系. 当代码中出现异常的时候, 我们就可以使用 e.printStackTrace(); 的 方式查看出现异常代码的调用栈. 如果本方法中没有合适的处理异常的方式, **就会沿着调用栈向上传递 **</p> 
<pre><code>public class Test {


    public static final void func1(){

        int[] a={1,2,3,4,5};
        a[10] = 100;



    }

    public static void main(String[] args) {
        try {
           func1();
            System.out.println("hello world");
        }catch (ArrayIndexOutOfBoundsException e){
            e.printStackTrace();
            System.out.println("没能合适解决异常");

        }

    }
}
</code></pre> 
<p><img src="https://images2.imgbox.com/bf/57/DJHFfyby_o.png" alt="image.png"><br> 如上图：在func1中如果没进行处理，堆栈就会延栈调用，也就是图中又看mian方法中是否能够处理好异常，一直向上传递如果都无法解决，<strong>一旦交给JVM处理那么程序将会终止</strong>，就不会进行之后的代码。</p> 
<h6><a id="if_262"></a>异常类与if的区别</h6> 
<p>首先我们来说说if在应对程序的应用是怎样的？<br> <strong>if语句：</strong><br> 比如：下面代码我们的if就是在检测到b==0时,就不让程序继续进行下面的计算。<br> 这属于一种事先防卫型，就是避免错误发生。在发生之前就将程序阻断。</p> 
<pre><code>package demo1;

import java.util.Scanner;

public class Test {

    public static void main(String[] args) {
        Scanner sc=new Scanner(System.in);
        int a=sc.nextInt();
        int b=sc.nextInt();
        
        if(b==0){
            System.out.println("分母为0，数字不合法");
        }else {
            System.out.println("a/c= "+a/b);
        }
        
        
    }
}
</code></pre> 
<hr> 
<p><strong>异常类：</strong><br> <strong>如下：异常类相比于if更像是先斩后奏型，事后处理型，在程序发现问题时在进行处理问题，如下代码将可能有异常的语句放到try括号中，如果出现异常在进行解决：</strong></p> 
<pre><code>package demo1;

public class Test1 {

    public static void main(String[] args) {
        int a=10;
        int b=0;
        try{
            System.out.println("a/c= "+a/b);
        }catch (ArithmeticException e){
            System.out.println("捕捉到异常并解决异常的方法");
        }
    }
}
</code></pre>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/c615af6feb6748d5d6a450b1468c8954/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">Java 接口</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/352a6a61fa731a98508a25dbba1271cd/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">如何下载和安装SQLynx数据库管理工具? （MySQL作为测试数据库）</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大咖.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://www.w3counter.com/tracker.js?id=151347"></script>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>